# Total planning attempts
max_solutions: 10

# Planning group and link names
dual_arm_group: "dual_arm"
arm_1_group_name: "panda_1" #right arm
arm_2_group_name: "panda_2" #left arm
eef_1_name: "hand_1"
eef_2_name: "hand_2"
hand_1_group_name: "hand_1"
hand_2_group_name: "hand_2"
hand_1_frame: "panda_1_link8"
hand_2_frame: "panda_2_link8"

# Poses
hand_1_open_pose: "open"
hand_1_close_pose: "close"
arm_1_home_pose: "home"

hand_2_open_pose: "open"
hand_2_close_pose: "close"
arm_2_home_pose: "home"


# Scene frames
world_frame: "world"
table_reference_frame: "world"
object_reference_frame: "world"
obstacle_reference_frame: "world"
simple_obst_reference_frame: "world"
surface_1_link: "table_1"
surface_2_link: "table_2"

# Collision object for picking
# CYLINDER object specifications
object_name: "object"
object_dimensions: [0.25, 0.02] # [height, radius]
object_pose: [0.6, 0.5, 1.1, 0, 0, 0]


# Simple Obstacle
simple_obst_name: "pillar"
simple_obst_dimensions: [0.1, 0.1, 0.35]
simple_obst_pose: [0.45, 0.2, 1.0, 0.0, 0.0, 0.0]

# Obstacle specifications
obstacle_name: "obstacle"
obstacle_dimensions_0: [0.05, 0.05, 0.5]
obstacle_dimensions_1: [0.5, 0.05, 0.05]
obstacle_dimensions_2: [0.03, 0.2, 0.03]
obstacle_dimensions_3: [0.03, 0.03, 0.2]
obstacle_dimensions_4: [0.05, 0.05, 0.15]
obstacle_pose_0: [0.3, 0, 1.25, 0, 0, 0, 1]
obstacle_pose_1: [0.4, 0, 1.2, 0, 0, 0, 1]
obstacle_pose_2: [0.3, 0.125, 1.4, 0, 0, 0, 1]
obstacle_pose_3: [0.3, 0.24, 1.485, 0, 0, 0, 1]
obstacle_pose_4: [0.675, 0, 1.225, 0, 0, 0, 1]

# DLO model
dlo_name: "dynamic_object"
dlo_reference_frame: "world"

marker_name: "line_marker"
clockwise: true # If true, the gripper will wrap the DLO around the obstacle in a clockwise motion
                # if false, it will do the same in a counter clockwise motion

# Table model
spawn_table: false
table_1_name: "table_1"
table_1_dimensions: [0.4, 0.5, 0.1]  # [length, width, height]
table_1_pose: [0.6, 0.5, 1.0, 0, 0, 0]

table_2_name: "table_2"
table_2_dimensions: [0.4, 0.5, 0.1]  # [length, width, height]
table_2_pose: [0.6, -0.5, 1.0, 0, 0, 0]

# Gripper grasp frame transform [x,y,z,r,p,y]
grasp_frame_transform: [0, 0, 0.1, 1.571, 0.785, 1.571]

# # Place pose [x,y,z,r,p,y]
place_pose: [0.5, 0.0, 1.5, 0, 0, 0]
place_surface_offset: 0.0001 # place offset from table

# Point somewhere up for hand 1
up_pose: [0.0, 0.5, 1.8, 0, 0, 0]

# Center pose for DLO wrapping motion
center_pose_1: [0.3, -0.25, 1.3]
center_pose_2: [0.6, 0.5, 1.4] 
counterclockwise_pose: [0.3, 0.4, 1.3]
min_distance: 0.2
max_distance: 0.8


# Valid distance range when approaching an object for picking
approach_object_min_dist: 0.1
approach_object_max_dist: 0.15

# Valid height range when lifting an object after pick
lift_object_min_dist: 0.01
lift_object_max_dist: 0.1
